const olympicGames = [
  {
    id: 1,
    data_aos: "fade-up-right",
    a: "archery.php",
    name: "Archery",
    image: "sportsImages/archery.jpg",
  },
  {
    id: 2,
    data_aos: "fade-up",
    a: "badminton.php",
    name: "Badminton",
    image: "sportsImages/badminton.jpeg",
  },
  {
    id: 3,
    data_aos: "fade-up-left",
    a: "boxing.php",
    name: "Boxing",
    image: "sportsImages/boxing.jpg",
  },
  {
    id: 4,
    data_aos: "fade-up-right",
    a: "cycling.php",
    name: "Cycling",
    image: "sportsImages/cycling.jpg",
  },
  {
    id: 5,
    data_aos: "fade-up",
    a: "fencing.php",
    name: "Fencing",
    image: "sportsImages/fencing.jpg",
  },
  {
    id: 6,
    data_aos: "fade-up-left",
    a: "hockey.php",
    name: "Hockey",
    image: "sportsImages/hockey.jpg",
  },
  {
    id: 7,
    data_aos: "fade-up-right",
    a: "judo.php",
    name: "Judo",
    image: "sportsImages/judo.png",
  },
  {
    id: 8,
    data_aos: "fade-up",
    a: "tennis.php",
    name: "Table Tennis",
    image: "sportsImages/tableTennis.jpg",
  },
  {
    id: 9,
    data_aos: "fade-up-left",
    a: "volleyball.php",
    name: "Volleyball",
    image: "sportsImages/volleyball.jpg",
  },
];
