const olympicGames = [
  {
    id: "aa",
    data_aos: "fade-up-right",
    a: "archery.php",
    name: "Archery",
    image: "sportsImages/archery.jpg",
  },
  {
    id: "ab",
    data_aos: "fade-up",
    a: "badminton.php",
    name: "Badminton",
    image: "sportsImages/badminton.jpeg",
  },
  {
    id: "ac",
    data_aos: "fade-up-left",
    a: "boxing.php",
    name: "Boxing",
    image: "sportsImages/boxing.jpg",
  },
  {
    id: "ad",
    data_aos: "fade-up-right",
    a: "cycling.php",
    name: "Cycling",
    image: "sportsImages/cycling.jpg",
  },
  {
    id: "ae",
    data_aos: "fade-up",
    a: "fencing.php",
    name: "Fencing",
    image: "sportsImages/fencing.jpg",
  },
  {
    id: "af",
    data_aos: "fade-up-left",
    a: "hockey.php",
    name: "Hockey",
    image: "sportsImages/hockey.jpg",
  },
  {
    id: "ag",
    data_aos: "fade-up-right",
    a: "judo.php",
    name: "Judo",
    image: "sportsImages/judo.png",
  },
  {
    id: "ah",
    data_aos: "fade-up",
    a: "tennis.php",
    name: "Table Tennis",
    image: "sportsImages/tableTennis.jpg",
  },
  {
    id: "ai",
    data_aos: "fade-up-left",
    a: "volleyball.php",
    name: "Volleyball",
    image: "sportsImages/volleyball.jpg",
  },
];
